# Generated by Django 3.1.6 on 2021-04-21 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('firstname', models.CharField(max_length=25)),
                ('lastname', models.CharField(max_length=25)),
                ('email', models.EmailField(max_length=255, primary_key=True, serialize=False, unique=True)),
                ('country', models.CharField(max_length=48)),
                ('state', models.CharField(max_length=48)),
                ('phone', models.CharField(max_length=25)),
                ('is_admin', models.BooleanField(default=False)),
                ('picture', models.ImageField(blank=True, max_length=255, upload_to='staticfiels/')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
