# Generated by Django 3.1.6 on 2021-04-26 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20210426_1829'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='country',
            field=models.CharField(blank=True, default=1, max_length=48),
            preserve_default=False,
        ),
    ]
