# Generated by Django 3.1.6 on 2021-04-24 22:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banking', '0003_auto_20210424_1837'),
    ]

    operations = [
        migrations.AddField(
            model_name='transferrequest',
            name='transfer_type',
            field=models.CharField(choices=[('Intl', 'International Transfer'), ('local', 'Local Transfer')], default='local', max_length=25),
        ),
    ]
