# Generated by Django 3.1.6 on 2021-04-26 12:39

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('banking', '0006_auto_20210425_0059'),
    ]

    operations = [
        migrations.AddField(
            model_name='transferrequest',
            name='transaction_type',
            field=models.CharField(choices=[('credit', 'Credit'), ('debit', 'Debit')], default='debit', max_length=25, verbose_name='Transaction type'),
        ),
        migrations.AlterField(
            model_name='transferrequest',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2021, 4, 26, 12, 39, 41, 710352, tzinfo=utc)),
        ),
    ]
