# Generated by Django 3.1.6 on 2021-04-26 12:39

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('banking', '0007_auto_20210426_1339'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transferrequest',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
