# Generated by Django 3.1.6 on 2021-04-26 16:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('banking', '0008_auto_20210426_1339'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transferrequest',
            name='bank_iban',
        ),
    ]
