# Generated by Django 3.1.6 on 2021-04-26 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banking', '0009_remove_transferrequest_bank_iban'),
    ]

    operations = [
        migrations.AddField(
            model_name='transferrequest',
            name='city',
            field=models.CharField(max_length=48, null=True, verbose_name='City'),
        ),
    ]
