# Generated by Django 3.1.6 on 2021-05-01 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banking', '0010_transferrequest_city'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transferrequest',
            name='bank_swift',
        ),
        migrations.AddField(
            model_name='transferrequest',
            name='ifto_code',
            field=models.CharField(default='null', max_length=48),
            preserve_default=False,
        ),
    ]
