# Generated by Django 3.1.6 on 2021-05-01 10:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('banking', '0011_auto_20210501_1102'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transferrequest',
            old_name='ifto_code',
            new_name='ifsc_code',
        ),
    ]
