# Generated by Django 3.1.6 on 2021-05-01 10:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('banking', '0012_auto_20210501_1113'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transferrequest',
            old_name='bank_address',
            new_name='bank_branch',
        ),
    ]
