# Generated by Django 3.1.6 on 2021-05-01 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banking', '0013_auto_20210501_1113'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transferrequest',
            name='ifsc_code',
            field=models.CharField(max_length=48, null=True),
        ),
    ]
