# Generated by Django 3.1.6 on 2021-05-01 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banking', '0014_auto_20210501_1449'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='otp',
            options={'verbose_name': 'IFSC Code', 'verbose_name_plural': 'IFSC Codes'},
        ),
        migrations.AddField(
            model_name='otp',
            name='used',
            field=models.BooleanField(default=False),
        ),
    ]
