# Generated by Django 3.1.6 on 2021-05-02 16:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('banking', '0015_auto_20210501_1549'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='otp',
            options={'verbose_name': 'COT Code', 'verbose_name_plural': 'COT Codes'},
        ),
    ]
