# Generated by Django 3.1.6 on 2021-05-26 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banking', '0016_auto_20210502_1629'),
    ]

    operations = [
        migrations.AddField(
            model_name='transferrequest',
            name='deducted',
            field=models.BooleanField(default=False, editable=False),
        ),
    ]
